version: "3.8"

services:
  #サービス（コンテナ）
  db:
    #ベースイメージを定義
    image: postgres:13.1-alpine
    #環境変数を定義
    environment:
      #OSのタイムゾーン
      TZ: UTC
      #postgresのタイムゾーン
      PGTZ: UTC
      #データベースのパスワード
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    #ホスト側のディレクトリをコンテナで使用する
    #volumes:ホストパス(絶対or相対):コンテナパス(絶対)
    volumes:
      - "./api/tmp/db:/var/lib/postgresql/data"

  api:
    #ベースイメージとなるDockerfileを指定
    build:
      context: ./api
      # Dockerfileに変数を渡す
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "./api:/$WORKDIR"
    #サービスの依存関係を定義(起動の順番)
    depends_on:
      - db
    #公開ポートを指定
    #公開したいポート番号:コンテナポート
    ports:
      - "$API_PORT:3000"

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        #CONTAINER_PORT: $CONTAINER_PORT
    #コンテナで実行したいコマンド(CMD)
    command: yarn run dev
    volumes:
      - "./front:/$WORKDIR"
    ports:
      - "$FRONT_PORT:3000"
    depends_on:
      - api